# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('hruid', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(blank=True, max_length=40)),
                ('token', models.CharField(blank=True, max_length=32)),
                ('weak_password', models.CharField(blank=True, max_length=256)),
                ('user_perms', models.CharField(blank=True, max_length=96)),
                ('is_admin', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(max_length=8)),
                ('flags', models.CharField(max_length=5)),
                ('registration_date', models.DateTimeField()),
                ('firstname', models.CharField(blank=True, max_length=255)),
                ('lastname', models.CharField(blank=True, max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('directory_name', models.CharField(blank=True, max_length=255)),
                ('sort_name', models.CharField(blank=True, max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('from_email', models.CharField(max_length=255)),
                ('from_format', models.CharField(max_length=4)),
                ('sex', models.CharField(max_length=6)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('email_format', models.CharField(max_length=4)),
                ('last_version', models.CharField(max_length=16)),
            ],
            options={
                'managed': True,
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='AccountTypes',
            fields=[
                ('type', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('perms', models.CharField(max_length=124)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'managed': True,
                'db_table': 'account_types',
            },
        ),
        migrations.CreateModel(
            name='EmailVirtualDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aliasing', models.ForeignKey(db_column='aliasing', on_delete=django.db.models.deletion.CASCADE, to='platal_auth.EmailVirtualDomains')),
            ],
            options={
                'managed': True,
                'db_table': 'email_virtual_domains',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='best_domain',
            field=models.ForeignKey(blank=True, db_column='best_domain', null=True, on_delete=django.db.models.deletion.CASCADE, to='platal_auth.EmailVirtualDomains'),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.ForeignKey(blank=True, db_column='type', null=True, on_delete=django.db.models.deletion.CASCADE, to='platal_auth.AccountTypes'),
        ),
    ]
