# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 21:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platal_auth', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfileLink',
            fields=[
                ('account', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_links', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('perms', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'account_profiles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('hrpid', models.CharField(max_length=255, unique=True)),
                ('xorg_id', models.IntegerField()),
                ('ax_id', models.CharField(blank=True, max_length=8)),
                ('last_change', models.DateField()),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('birthdate_ref', models.DateField(blank=True, null=True)),
                ('next_birthday', models.DateField(blank=True, null=True)),
                ('deathdate', models.DateField(blank=True, null=True)),
                ('deathdate_rec', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=4)),
                ('sex', models.CharField(max_length=6)),
                ('email_directory', models.CharField(blank=True, max_length=255)),
                ('cv', models.TextField(blank=True)),
                ('freetext', models.TextField(blank=True)),
                ('axfreetext', models.TextField(blank=True)),
                ('freetext_pub', models.CharField(max_length=7)),
                ('medals_pub', models.CharField(max_length=7)),
                ('alias_pub', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'profiles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProfileDisplay',
            fields=[
                ('profile', models.OneToOneField(db_column='pid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile_display', serialize=False, to='platal_profiles.Profile')),
                ('yourself', models.CharField(max_length=255)),
                ('public_name', models.CharField(max_length=255)),
                ('private_name', models.CharField(max_length=255)),
                ('directory_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
                ('sort_name', models.CharField(max_length=255)),
                ('promo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'profile_display',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('profile', models.OneToOneField(db_column='pid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='photo', serialize=False, to='platal_profiles.Profile')),
                ('attachmime', models.CharField(max_length=4)),
                ('attach', models.BinaryField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('pub', models.CharField(max_length=7)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'profile_photos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProfilePublicName',
            fields=[
                ('profile', models.OneToOneField(db_column='pid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='public_names', serialize=False, to='platal_profiles.Profile')),
                ('lastname_initial', models.CharField(max_length=255)),
                ('lastname_main', models.CharField(max_length=255)),
                ('lastname_marital', models.CharField(max_length=255)),
                ('lastname_ordinary', models.CharField(max_length=255)),
                ('firstname_initial', models.CharField(max_length=255)),
                ('firstname_main', models.CharField(max_length=255)),
                ('firstname_ordinary', models.CharField(max_length=255)),
                ('pseudonym', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'profile_public_names',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='accounts',
            field=models.ManyToManyField(related_name='profiles', through='platal_profiles.AccountProfileLink', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountprofilelink',
            name='profile',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, related_name='account_links', to='platal_profiles.Profile'),
        ),
    ]
